#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#000"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#7ccdfd"
bspc config presel-feedback_colour "#fc9d63"

bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

# eww open bar
