#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 10

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#414868"
bspc config active_border_color "#7dcfff"
bspc config focused_border_color "#7dcfff"
bspc config presel_feedback_color "#15161e"

bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a matplotlib state=floating
