#!/bin/sh

# Launch Polybar
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 10

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a matplotlib state=floating
bspc rule -a pavucontrol state=floating rectangle=473x288+1431+54 focus=off follow=off sticky=on
bspc rule -a Gsimplecal state=floating rectangle=250x188+1654+52 focus=off follow=off sticky=on

. "$HOME/.config/daub/gen/colors.sh"
bspc config normal_border_color "$background1"
bspc config active_border_color "$color4"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$background1"
